### ISSUE TITLE
sending photos from the camera

### ISSUE THREAD

**Issue by harishpillay** [kylecorry31/ML4K-AI-Extension#13]
I am trying to get photo taken from the phone to be sent to a model I've trained but it comes back with the error 400. Here's the image: https://photos.app.goo.gl/VAB7as5voqbr3Fz16. The image that is in the phone is a .jpg and the logic is similar to your example. Any hints?

**Comment by kylecorry31** [comment]
It appears this issue is widespread. I'll have time to take a look later this week
