### ISSUE TITLE
Using the camera with image classification doesn't attach data

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/ML4K-AI-Extension#17]
From @dalelane in #16
"If I use the Camera, then the data seems to be missing from the classification request. (I just got a HTTP 400 Missing data error response)"

**Comment by kylecorry31** [comment]
@dalelane I believe this issue is fixed (at least with my device), and is in need of testing. Could you test with your device? The .aix file is attached.
[ML4K.zip](https://github.com/kylecorry31/ML4K-AI-Extension/files/2742900/ML4K.zip)

**Comment by dalelane** [comment]
@kylecorry31 That worked perfectly, thanks!

**Comment by dalelane** [comment]
It meant we could make this :-) 

https://youtu.be/dIjU6rmuoGc

**Comment by kylecorry31** [comment]
That example is really cool, thanks!
