### ISSUE TITLE
Bad response from server:404

### ISSUE THREAD

**Issue by bh26** [kylecorry31/ML4K-AI-Extension#23]
Hello, I tried to follow some tricks from this post below, hence the reference.
I am trying to solve a similar issue but I cannot get it to work.
I am trying the example CirclesAndRectangles.aia
Actually I did everything that was needed on ML4K site, and got the URL for the extension. I understand from another issue that the API Key was included in the extension.
Anyway I added the API key in the Screen.Initialize block
But whatever I do I get "Bad response by server:404"
I did it on 2 different phones once with the companion and once with .apk, all with the same result.
What could I have done wrong?
Thanks
__________________________________________________________
Hello Kyle, now it works! 

I'm not sure if solution was new version, or problem was that I made so many tests and so many apps with different mi4k projects that my phone (two phones, actually) had charged in memory an incorrect version of extension.  In case it is usefull, I tell you about the process

I have tested an app make by Dale Lane with my key, and at first It didn't work in my phones. I have installed this app in a third phone (with no other app with MI4K installed) ... and it worked!

I had to uninstall from my phones all different apps and versions I generated with app inventor and ML4K extension, I've reboot my phone and installed only one version (new extension?)....and it runned!

This is a project of my son and some friends, and I was helping them to solve the problem.

**Thank you very much!**

_Originally posted by @gsebastia in https://github.com/kylecorry31/ML4K-AI-Extension/issues/20#issuecomment-453870144_

**Comment by dalelane** [comment]
@bh26 I'm happy to help investigate if I can. The easiest way for me to see what is happening would be if you could send me a copy of your project (my email address is on [my profile](https://github.com/Dalelane) page) so I can try it for myself.

**Comment by MrMazzone** [comment]
Hi @bh26 , I believe it is due to an old extension file in that .aia file example on the Github page.  I will update.  Can you download this project below, paste your key into the "ML4K1" component's "Key" property on Designer, and test to see if it works?  Don't forget to make sure your model is trained.

Download here: https://1drv.ms/u/s!Ap8cS8TATIfLuqo2fBJmCfGze5rCTA?e=lvcFFl

**Comment by bh26** [comment]
Thanks Dale, I sent you the url.
Thanks Joe, I downloaded and ran it on my mobile but I got the same error.
Actually I had found that for the project it was possible to get an URL and pass this url to the import extension from url box in AI.
Just as an information, I created an unmanaged account on ML4K, and followed the steps on IBM watson.
Actually the API key I put in AI was the one provided by IBM to ML4K. I hope that is correct.
Bernard

**Comment by MrMazzone** [comment]
Hi Bernard @bh26 
That is your problem. You need to provide your project key, not the IBM Watson API key.  The extension needs a way to tie your App Inventor project extension with your Machine Learning for Kids project/ML model, so there is a unique project key.

It can be found in the URL you described. See highlighted section.
![image](https://user-images.githubusercontent.com/40954645/62778346-291e2d80-ba7e-11e9-8ace-236340982005.png)

You can also easily see it here in the Python project section:
![image](https://user-images.githubusercontent.com/40954645/62778444-68e51500-ba7e-11e9-861f-e8cad32165be.png)

Essentially, the system is designed so you do not need to provide the key; unless you use my example .aia files.  If you import the extension with the URL it will automatically add the key and you do not need to add it on Designer or Blocks in App Inventor.

**Comment by bh26** [comment]
AAAAH!
I thought there was something like that but I thought since the extension was already connected to the project via the URL the API key in the blocks was not important. But without an API key in the designer it does not work with error "no API key".
And the documentation (?) is not very clear on that.
Anyway, that works quite well.
Actually, in which case the Extension importing via the URL makes the API key in the Designer irrelevant, if any?
Thanks,

**Comment by MrMazzone** [comment]
@bh26 Correct, importing the URL makes the API key in Designer irrelevant. Only when you come here to the GitHub page does it get confusing when looking at my examples. 

I'll add some documentation to clarify getting the project key to use the examples.

**Comment by bh26** [comment]
OK, but how to overcome the "No API key" error message? or should we not care?

**Comment by MrMazzone** [comment]
@bh26 That should only happen when using the .aix extension file from this Github page when you do not provide the key.  When you use the URL to import the extension from the Machine Learning for Kids site, it automatically adds the key for you.

Were you getting this error from the example project file, .aix from GitHub, or URL added extension?

**Comment by bh26** [comment]
I retested it properly without the key in the designer and I don't get the
error.
There are a few tricks to know but when it works it's like magic.
Very nice actually.
Bernard Haddad
-- Disclaimer ----------
Important Note: This e-mail may contain trade secrets or privileged,
undisclosed or otherwise confidential information. If you have received
this e-mail in error, you are hereby notified that any review, copying or
distribution of it is strictly prohibited. Please inform us immediately and
destroy the original transmittal. Thank you for your cooperation.

**Comment by MrMazzone** [comment]
Thanks for the follow-up, Bernard.  We will continue to make the extension have fewer tricks and more pure magic! 😉

Unless there is anything else @bh26 , I am going to have @kylecorry31 close this issue.
