### ISSUE TITLE
Crash in older Android version

### ISSUE THREAD

**Issue by dalelane** [kylecorry31/ML4K-AI-Extension#34]
_This was sent to me by email by a user. I'm just passing it on, and haven't had a chance to attempt to recreate myself._ 

Attempts to use ML4K extension blocks crashed the App Inventor app, with the following:

```
E/AndroidRuntime(  283): FATAL EXCEPTION: Thread-17
E/AndroidRuntime(  283): java.lang.NoSuchMethodError: java.lang.String.isEmpty
E/AndroidRuntime(  283):        at com.kylecorry.ml4k.ML4K.setAPIKey(ML4K.java:48)
E/AndroidRuntime(  283):        at com.kylecorry.ml4k.ML4K.<init>(ML4K.java:39)
E/AndroidRuntime(  283):        at com.kylecorry.ml4k.ML4KComponent$2.run(ML4KComponent.java:88)
E/AndroidRuntime(  283):        at java.lang.Thread.run(Thread.java:1096)
```

**Comment by kylecorry31** [comment]
@dalelane This is an issue on android 2.3, the latest commit on master fixes this issue. I will try to close the other issue this week as well (with the numbers data)

**Comment by dalelane** [comment]
Thanks!
