### ISSUE TITLE
how to get the API KEY ( error : API key isn't a machine learning for kids key )

### ISSUE THREAD

**Issue by karlTH** [kylecorry31/ML4K-AI-Extension#36]
Hello, i've try many things but i don't arrive to have an apikey who work.

Wheni'm going on : [https://machinelearningforkids.co.uk/#!/teacher/apikeys](https://machinelearningforkids.co.uk/#!/teacher/apikeys)
They say : no apiket need for images cmlassification
I've been on : [https://cloud.ibm.com/](https://cloud.ibm.com/)
I've create an account and get an apikey like it's say here :
[https://raw.githubusercontent.com/IBM/taxinomitis-docs/master/docs/pdf/machinelearningforkids-apikeys.pdf
](https://raw.githubusercontent.com/IBM/taxinomitis-docs/master/docs/pdf/machinelearningforkids-apikeys.pdf
)With this apikey in app inventor :
the block error return the error : API key isn't a machine learning for kids key

What should i do ? and how
Thanks a lot for the extension

**Comment by MrMazzone** [comment]
Hi @karlTH .

When you create a project on Machine Learning for Kids and select App Inventor, you will see instructions on how to add the extension.  If you add the extension this way, no need to add a Machine Learning for Kids key.  It is automatically added for you.
![image](https://user-images.githubusercontent.com/40954645/112541699-127b3600-8d8a-11eb-8112-d2a2c97823d9.png)

It you want to manually set it, you can see the key in the URL you use for the extension.

**Comment by karlTH** [comment]
Thanks
but i don't find where to  select App Inventor in Machine Learning for Kids
i just see scratch and python
did you have a link ? or add a link in the README.md
thanks a lot

**Comment by dalelane** [comment]
Please see "Why can I only make something with Scratch or Python for my machine learning project?" in the FAQs on https://machinelearningforkids.co.uk/help
