### ISSUE TITLE
Only one model out of three is trained

### ISSUE THREAD

**Issue by HiSuzanneLee** [kylecorry31/ML4K-AI-Extension#44]
Hello, I have trained three separate image recognition models on machinelearningforkids.co.uk and put them in an app inventor app. However, when I try to classify an image, only one machine learning model is functional, and the other two displays a 'not trained' warning. The code for all three models are the same, and have been trained with the train new model block, but it just isn't working.

**Comment by dalelane** [comment]
@HiSuzanneLee  - is this no longer a problem?
